name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/30 * * * *" # every 15 minutes
  workflow_dispatch: # allows you to run manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://your-streamlit-app-url.streamlit.app
