name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/30 * * * *"
    - cron: "0 12 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://your-streamlit-app-url.streamlit.app

  weekly_commit:
    if: github.event.schedule == '0 12 * * 1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "🫀 keep-alive: weekly heartbeat"
          git push origin HEAD:main
