name: Send Notion Review Emails

on:
  schedule:
    # Runs every Monday at 8 AM EST (13:00 UTC)
    - cron: '0 13 * * 1'
    # - cron: '*/10 * * * *'
  workflow_dispatch:  # allow manual trigger too

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Notion job
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_DATA_SOURCE_ID: ${{ secrets.NOTION_DATA_SOURCE_ID }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_URL: ${{ secrets.GOOGLE_API_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python src/run_notion_job.py
